# Generated by Django 3.0.7 on 2021-05-06 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0010_auto_20210506_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_model',
            name='total_gst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 36, 6, 749568)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 36, 6, 749568)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 36, 6, 749568)),
        ),
    ]
