# Generated by Django 3.2.1 on 2021-05-06 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0013_auto_20210506_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='rml_model',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 17, 27, 712741)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 17, 27, 712741)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 17, 27, 711742)),
        ),
        migrations.AlterField(
            model_name='rml_model',
            name='rml_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='rml_model',
            unique_together={('project_no', 'rml_no')},
        ),
    ]
