# Generated by Django 3.2.1 on 2021-05-06 21:40

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0014_auto_20210506_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 40, 23, 659011)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 40, 23, 659011)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 40, 23, 659011)),
        ),
        migrations.AlterField(
            model_name='rml_model',
            name='available',
            field=models.IntegerField(default=django.db.models.expressions.F('allocate')),
        ),
    ]
