# Generated by Django 3.2.1 on 2021-05-06 21:46

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0015_auto_20210506_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 46, 40, 430560)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 46, 40, 430560)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 46, 40, 429579)),
        ),
        migrations.AddConstraint(
            model_name='rml_model',
            constraint=models.CheckConstraint(check=models.Q(('utilized__lte', django.db.models.expressions.F('allocate'))), name='tenderapp_rml_model_utilized_lte_allocate'),
        ),
    ]
