# Generated by Django 3.2.1 on 2021-05-08 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0017_auto_20210506_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_model',
            name='PO_Issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 23, 52, 700653)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 23, 52, 700653)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 23, 52, 699652)),
        ),
    ]
