# Generated by Django 3.2.1 on 2021-05-08 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0018_auto_20210508_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_model',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='request_model',
            name='request_by',
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 13, 22, 28, 396319)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 13, 22, 28, 396319)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 13, 22, 28, 395313)),
        ),
    ]
