# Generated by Django 3.2.1 on 2021-05-08 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0019_auto_20210508_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 13, 28, 23, 104676)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 13, 28, 23, 104676)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 13, 28, 23, 104676)),
        ),
        migrations.AlterField(
            model_name='request_model',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 13, 28, 23, 105676)),
        ),
        migrations.AlterField(
            model_name='request_model',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
