# Generated by Django 3.1.7 on 2021-05-15 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0020_auto_20210508_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='rml_model',
            name='attachment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rml_model',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rml_model',
            name='specification',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rml_model',
            name='unit',
            field=models.CharField(default='Nos', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 12, 36, 46, 906310)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 12, 36, 46, 906310)),
        ),
        migrations.AlterField(
            model_name='project_model',
            name='project_no',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 12, 36, 46, 906310)),
        ),
        migrations.AlterField(
            model_name='request_model',
            name='date',
            field=models.DateTimeField(default='2021-05-15'),
        ),
        migrations.AlterField(
            model_name='request_model',
            name='project_no',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='rml_model',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rml_model',
            name='rml_no',
            field=models.CharField(max_length=40),
        ),
    ]
