# Generated by Django 3.1.7 on 2021-05-16 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0021_auto_20210515_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 9, 54, 56, 896308)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 9, 54, 56, 896308)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 9, 54, 56, 895274)),
        ),
        migrations.AlterField(
            model_name='request_model',
            name='date',
            field=models.DateTimeField(default='2021-05-16'),
        ),
    ]
