# Generated by Django 3.1.7 on 2021-05-16 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenderapp', '0022_auto_20210516_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_model',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 10, 17, 33, 911453)),
        ),
        migrations.AlterField(
            model_name='invoice_model',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 10, 17, 33, 911453)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 10, 17, 33, 911453)),
        ),
        migrations.AlterField(
            model_name='purchase_order_model',
            name='rml',
            field=models.CharField(max_length=40),
        ),
    ]
